name: Build and Release Chrome Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build vendor bundle
        run: npm run build

      - name: Package extension
        run: |
          set -e
          mkdir -p extension/scripts extension/vendor
          cp manifest.json hello.html extension/
          cp -r scripts/*.js extension/scripts/
          cp vendor/faker-bundle.js extension/vendor/
          if [ -f README.md ]; then cp README.md extension/; fi
          cd extension
          zip -r ../dev-qa-tools-${GITHUB_REF_NAME}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dev-qa-tools-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
